import { useState, useEffect } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity, StyleSheet,
  ActivityIndicator,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { theme } from '../../constants/theme';
import useFraudCheck from '../../hooks/useFraudCheck';

export default function PredictorScreen() {
  const { getPredictions } = useFraudCheck();
  const [predictions, setPredictions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [lastUpdated, setLastUpdated] = useState('');

  const load = async () => {
    setLoading(true);
    const data = await getPredictions();
    setPredictions(data?.predictions || []);
    setLastUpdated(new Date(data?.updated_at || Date.now()).toLocaleTimeString('en-IN'));
    setLoading(false);
  };

  useEffect(() => { load(); }, []);

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.title}>🤖 AI Scam Intelligence</Text>
            <Text style={styles.subtitle}>Powered by Claude · Updated {lastUpdated || '—'}</Text>
          </View>
          <TouchableOpacity onPress={load} style={styles.refreshBtn} disabled={loading}>
            {loading ? (
              <ActivityIndicator size="small" color={theme.colors.primary} />
            ) : (
              <Ionicons name="refresh" size={22} color={theme.colors.primary} />
            )}
          </TouchableOpacity>
        </View>

        {/* Alert Banner */}
        <LinearGradient colors={['#EF444420', '#0A0F1E00']} style={styles.alertBanner}>
          <Ionicons name="trending-up" size={20} color={theme.colors.danger} />
          <Text style={styles.alertBannerText}>
            Scam activity is <Text style={{ color: theme.colors.danger, fontWeight: '700' }}>+235% higher</Text> than last month in metro cities
          </Text>
        </LinearGradient>

        {loading && predictions.length === 0 ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color={theme.colors.primary} />
            <Text style={styles.loadingText}>Consulting Claude AI...</Text>
          </View>
        ) : (
          predictions.map((p, i) => (
            <PredictionCard key={i} prediction={p} rank={i + 1} />
          ))
        )}

        {/* Info Footer */}
        <View style={styles.footer}>
          <Ionicons name="information-circle" size={16} color={theme.colors.textMuted} />
          <Text style={styles.footerText}>
            Predictions are generated by Claude AI using live fraud pattern data. Refresh for latest insights.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

function PredictionCard({ prediction: p, rank }) {
  const [expanded, setExpanded] = useState(rank === 1);
  const isTrending = rank <= 2;

  return (
    <TouchableOpacity onPress={() => setExpanded(!expanded)} activeOpacity={0.85}>
      <View style={[styles.card, isTrending && styles.trendingCard]}>
        {/* Rank Badge */}
        {isTrending && (
          <View style={styles.trendingBadge}>
            <Text style={styles.trendingText}>🚨 TRENDING</Text>
          </View>
        )}

        <View style={styles.cardHeader}>
          <View style={styles.cardLeft}>
            <Text style={styles.scamType}>{p.scam_type}</Text>
            <View style={styles.cityRow}>
              <Ionicons name="location" size={13} color={theme.colors.textMuted} />
              <Text style={styles.city}>{p.city}</Text>
            </View>
          </View>
          <Ionicons name={expanded ? 'chevron-up' : 'chevron-down'} size={18} color={theme.colors.textMuted} />
        </View>

        {/* Stats Row */}
        <View style={styles.statsRow}>
          <StatChip icon="alert-circle" value={`${p.reports_24h} reports`} color={theme.colors.danger} />
          <StatChip icon="trending-up" value={p.trend} color={theme.colors.warning} />
        </View>

        {/* Alert Message */}
        <View style={styles.alertBox}>
          <Ionicons name="warning" size={14} color={theme.colors.warning} />
          <Text style={styles.alertMessage}>{p.alert_message}</Text>
        </View>

        {/* Expanded: How it works */}
        {expanded && (
          <View style={styles.expanded}>
            <View style={styles.divider} />
            <Text style={styles.expandedLabel}>How it works:</Text>
            <Text style={styles.expandedText}>{p.common_pattern}</Text>
            <View style={styles.protectedBadge}>
              <Ionicons name="shield-checkmark" size={14} color={theme.colors.safe} />
              <Text style={styles.protectedText}>🛡️ FraudShield detects this pattern automatically</Text>
            </View>
          </View>
        )}
      </View>
    </TouchableOpacity>
  );
}

const StatChip = ({ icon, value, color }) => (
  <View style={[styles.chip, { backgroundColor: color + '18', borderColor: color + '40' }]}>
    <Ionicons name={icon} size={12} color={color} />
    <Text style={[styles.chipText, { color }]}>{value}</Text>
  </View>
);

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  scroll: { paddingHorizontal: 16, paddingBottom: 30 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16 },
  title: { fontSize: 20, fontWeight: '800', color: theme.colors.textPrimary },
  subtitle: { fontSize: 11, color: theme.colors.textMuted, marginTop: 2 },
  refreshBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.card, borderRadius: 20, borderWidth: 1, borderColor: theme.colors.cardBorder },
  alertBanner: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, padding: 14, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.danger + '30', marginBottom: 16 },
  alertBannerText: { flex: 1, fontSize: 13, color: theme.colors.textSecondary, lineHeight: 18 },
  loadingContainer: { alignItems: 'center', paddingVertical: 60, gap: 14 },
  loadingText: { color: theme.colors.textSecondary, fontSize: 14 },
  card: {
    backgroundColor: theme.colors.card, borderRadius: theme.borderRadius.xl,
    borderWidth: 1, borderColor: theme.colors.cardBorder,
    padding: 16, marginBottom: 14,
  },
  trendingCard: { borderColor: theme.colors.danger + '50', borderWidth: 1.5 },
  trendingBadge: { backgroundColor: theme.colors.dangerGlow, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4, alignSelf: 'flex-start', marginBottom: 10, borderWidth: 1, borderColor: theme.colors.danger + '40' },
  trendingText: { fontSize: 11, fontWeight: '700', color: theme.colors.danger, letterSpacing: 0.5 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  cardLeft: { flex: 1 },
  scamType: { fontSize: 16, fontWeight: '800', color: theme.colors.textPrimary, marginBottom: 4 },
  cityRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  city: { fontSize: 12, color: theme.colors.textMuted },
  statsRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20, borderWidth: 1 },
  chipText: { fontSize: 12, fontWeight: '600' },
  alertBox: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: theme.colors.warningGlow, borderRadius: 10, padding: 10, borderWidth: 1, borderColor: theme.colors.warning + '30' },
  alertMessage: { flex: 1, fontSize: 12, color: theme.colors.textSecondary, lineHeight: 17 },
  expanded: { marginTop: 12 },
  divider: { height: 1, backgroundColor: theme.colors.cardBorder, marginBottom: 12 },
  expandedLabel: { fontSize: 12, fontWeight: '700', color: theme.colors.primary, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  expandedText: { fontSize: 13, color: theme.colors.textSecondary, lineHeight: 20, marginBottom: 10 },
  protectedBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: theme.colors.safeGlow, borderRadius: 8, padding: 8, borderWidth: 1, borderColor: theme.colors.safe + '40' },
  protectedText: { fontSize: 12, color: theme.colors.safe, fontWeight: '600', flex: 1 },
  footer: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginTop: 8 },
  footerText: { flex: 1, fontSize: 11, color: theme.colors.textMuted, lineHeight: 16 },
});
